require "RubyFits"
include Fits

templateString=<<EOS
XTENSION=BINTABLE
EXTNAME=TEST
TFORM#=I
TTYPE#=NUMBER

TFORM#=PD
TTYPE#=DOUBLE_ARRAY

COMMENT This is a sample FITS file generated by createNewTableFromTemplate.rb.
COMMENT The first column is of 16-bit signed integer type, and the second one
COMMENT is of variable-length double-precision floating-point number.
EOS

fitsFile=FitsFile.constructFromTemplateString(templateString)
hdu=fitsFile[1]

array=[]
nRows=100
hdu.resize(nRows)
for i in 0...nRows
	hdu["NUMBER"][i]=i
	array << Math.sqrt(i)
	hdu["DOUBLE_ARRAY"][i]=array
end

fitsFile.saveToFile("tableCreatedFromTemplate.fits")
